# Generated by Django 6.0.2 on 2026-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('context', '0003_add_version_remove_scope_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['-created_at'], 'verbose_name': 'Référentiel', 'verbose_name_plural': 'Référentiels'},
        ),
        migrations.RemoveField(
            model_name='framework',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='historicalframework',
            name='scope',
        ),
        migrations.AddField(
            model_name='framework',
            name='scopes',
            field=models.ManyToManyField(related_name='frameworks', to='context.scope', verbose_name='Périmètres'),
        ),
    ]
