# Generated by Django 6.0.2 on 2026-02-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_framework_options_remove_framework_scope_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exigence', 'verbose_name_plural': 'Exigences'},
        ),
        migrations.RemoveField(
            model_name='historicalrequirement',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='scope',
        ),
    ]
