# Generated by Django 5.2.11 on 2026-02-28 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_assetdependency_options_and_more"),
        ("compliance", "0003_alter_requirement_options_and_more"),
        ("context", "0008_alter_activity_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessmentresult",
            options={
                "ordering": ["requirement__order"],
                "verbose_name": "Assessment result",
                "verbose_name_plural": "Assessment results",
            },
        ),
        migrations.AlterModelOptions(
            name="complianceactionplan",
            options={
                "verbose_name": "Compliance action plan",
                "verbose_name_plural": "Compliance action plans",
            },
        ),
        migrations.AlterModelOptions(
            name="complianceassessment",
            options={
                "verbose_name": "Compliance assessment",
                "verbose_name_plural": "Compliance assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="framework",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Framework",
                "verbose_name_plural": "Frameworks",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassessmentresult",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Assessment result",
                "verbose_name_plural": "historical Assessment results",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcomplianceactionplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Compliance action plan",
                "verbose_name_plural": "historical Compliance action plans",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcomplianceassessment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Compliance assessment",
                "verbose_name_plural": "historical Compliance assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalframework",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Framework",
                "verbose_name_plural": "historical Frameworks",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrequirement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Requirement",
                "verbose_name_plural": "historical Requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrequirementmapping",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Cross-framework mapping",
                "verbose_name_plural": "historical Cross-framework mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="requirement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="requirementmapping",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Cross-framework mapping",
                "verbose_name_plural": "Cross-framework mappings",
            },
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="assessed_at",
            field=models.DateTimeField(verbose_name="Assessment date"),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="assessed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assessor",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="compliance.complianceassessment",
                verbose_name="Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="compliance_level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Compliance level (%)"
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("non_compliant", "Non-compliant"),
                    ("partially_compliant", "Partially compliant"),
                    ("compliant", "Compliant"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=25,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="evidence",
            field=models.TextField(blank=True, default="", verbose_name="Evidence"),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="gaps",
            field=models.TextField(blank=True, default="", verbose_name="Gaps"),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_results",
                to="compliance.requirement",
                verbose_name="Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_plans",
                to="compliance.complianceassessment",
                verbose_name="Source assessment",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Completion date"
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="cost_estimate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost estimate",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="gap_description",
            field=models.TextField(verbose_name="Gap description"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_action_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="progress_percentage",
            field=models.PositiveIntegerField(default=0, verbose_name="Progress (%)"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="reference",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="remediation_plan",
            field=models.TextField(verbose_name="Remediation plan"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_plans",
                to="compliance.requirement",
                verbose_name="Related requirement",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("overdue", "Overdue"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="target_date",
            field=models.DateField(verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="assessment_date",
            field=models.DateField(verbose_name="Assessment date"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="assessor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="led_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lead assessor",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="compliant_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Compliant"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="compliance.framework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="methodology",
            field=models.TextField(blank=True, default="", verbose_name="Methodology"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="non_compliant_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Non-compliant"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="not_assessed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Not assessed"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="overall_compliance_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Overall compliance level (%)",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="partially_compliant_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Partially compliant"
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("validated", "Validated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="total_requirements",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total applicable requirements"
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Validation date"
            ),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated by",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="applicability_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Applicability justification"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="category",
            field=models.CharField(
                choices=[
                    ("information_security", "Information security"),
                    ("privacy", "Data protection"),
                    ("risk_management", "Risk management"),
                    ("business_continuity", "Business continuity"),
                    ("cloud_security", "Cloud security"),
                    ("sector_specific", "Sector-specific regulations"),
                    ("it_governance", "IT governance"),
                    ("quality", "Quality"),
                    ("contractual", "Contractual requirements"),
                    ("internal", "Internal policies"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="compliance_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Compliance level (%)",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="effective_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Effective date"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry date"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="framework_version",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Framework version"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="is_mandatory",
            field=models.BooleanField(default=False, verbose_name="Mandatory"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="issuing_body",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Issuing body"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="jurisdiction",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Jurisdiction"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="last_assessment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last assessment"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_frameworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="publication_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Publication date"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="reference",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="related_stakeholders",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_frameworks",
                to="context.stakeholder",
                verbose_name="Interested parties",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="scopes",
            field=models.ManyToManyField(
                related_name="frameworks", to="context.scope", verbose_name="Scopes"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="short_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Abbreviation"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("under_review", "Under review"),
                    ("deprecated", "Deprecated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("law", "Law"),
                    ("regulation", "Regulation"),
                    ("contract", "Contract"),
                    ("internal_policy", "Internal policy"),
                    ("industry_framework", "Industry framework"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Official link"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="assessed_at",
            field=models.DateTimeField(verbose_name="Assessment date"),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assessor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.complianceassessment",
                verbose_name="Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="compliance_level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Compliance level (%)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("non_compliant", "Non-compliant"),
                    ("partially_compliant", "Partially compliant"),
                    ("compliant", "Compliant"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=25,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="evidence",
            field=models.TextField(blank=True, default="", verbose_name="Evidence"),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="gaps",
            field=models.TextField(blank=True, default="", verbose_name="Gaps"),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.requirement",
                verbose_name="Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.complianceassessment",
                verbose_name="Source assessment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Completion date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="cost_estimate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost estimate",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="gap_description",
            field=models.TextField(verbose_name="Gap description"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="progress_percentage",
            field=models.PositiveIntegerField(default=0, verbose_name="Progress (%)"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="remediation_plan",
            field=models.TextField(verbose_name="Remediation plan"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.requirement",
                verbose_name="Related requirement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("overdue", "Overdue"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="target_date",
            field=models.DateField(verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="assessment_date",
            field=models.DateField(verbose_name="Assessment date"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lead assessor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="compliant_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Compliant"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.framework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="methodology",
            field=models.TextField(blank=True, default="", verbose_name="Methodology"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="non_compliant_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Non-compliant"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="not_assessed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Not assessed"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="overall_compliance_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Overall compliance level (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="partially_compliant_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Partially compliant"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("validated", "Validated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="total_requirements",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total applicable requirements"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Validation date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="applicability_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Applicability justification"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="category",
            field=models.CharField(
                choices=[
                    ("information_security", "Information security"),
                    ("privacy", "Data protection"),
                    ("risk_management", "Risk management"),
                    ("business_continuity", "Business continuity"),
                    ("cloud_security", "Cloud security"),
                    ("sector_specific", "Sector-specific regulations"),
                    ("it_governance", "IT governance"),
                    ("quality", "Quality"),
                    ("contractual", "Contractual requirements"),
                    ("internal", "Internal policies"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="compliance_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Compliance level (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="effective_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Effective date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry date"),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="framework_version",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Framework version"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="is_mandatory",
            field=models.BooleanField(default=False, verbose_name="Mandatory"),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="issuing_body",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Issuing body"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="jurisdiction",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Jurisdiction"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="last_assessment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last assessment"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="publication_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Publication date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="short_name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Abbreviation"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("under_review", "Under review"),
                    ("deprecated", "Deprecated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("law", "Law"),
                    ("regulation", "Regulation"),
                    ("contract", "Contract"),
                    ("internal_policy", "Internal policy"),
                    ("industry_framework", "Industry framework"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Official link"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="applicability_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Applicability justification"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organizational", "Organizational"),
                    ("technical", "Technical"),
                    ("physical", "Physical"),
                    ("legal", "Legal"),
                    ("human", "Human"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="compliance_evidence",
            field=models.TextField(
                blank=True, default="", verbose_name="Compliance evidence"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="compliance_gaps",
            field=models.TextField(
                blank=True, default="", verbose_name="Identified gaps"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="compliance_level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Compliance level (%)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("non_compliant", "Non-compliant"),
                    ("partially_compliant", "Partially compliant"),
                    ("compliant", "Compliant"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=25,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.framework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="guidance",
            field=models.TextField(
                blank=True, default="", verbose_name="Implementation guidance"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="last_assessed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last assessor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="last_assessment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last assessment"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="",
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="reference",
            field=models.CharField(max_length=100, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deprecated", "Deprecated"),
                    ("superseded", "Superseded"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="target_date",
            field=models.DateField(blank=True, null=True, verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("recommended", "Recommended"),
                    ("optional", "Optional"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="coverage_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Full"),
                    ("partial", "Partial"),
                    ("minimal", "Minimal"),
                ],
                default="",
                max_length=10,
                verbose_name="Coverage level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="mapping_type",
            field=models.CharField(
                choices=[
                    ("equivalent", "Equivalent"),
                    ("partial_overlap", "Partial overlap"),
                    ("includes", "Includes"),
                    ("included_by", "Included by"),
                    ("related", "Related"),
                ],
                max_length=20,
                verbose_name="Mapping type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="source_requirement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.requirement",
                verbose_name="Source requirement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="target_requirement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.requirement",
                verbose_name="Target requirement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementmapping",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="compliance_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Compliance level (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.framework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="parent_section",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.section",
                verbose_name="Parent section",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="reference",
            field=models.CharField(max_length=50, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="applicability_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Applicability justification"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organizational", "Organizational"),
                    ("technical", "Technical"),
                    ("physical", "Physical"),
                    ("legal", "Legal"),
                    ("human", "Human"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="compliance_evidence",
            field=models.TextField(
                blank=True, default="", verbose_name="Compliance evidence"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="compliance_gaps",
            field=models.TextField(
                blank=True, default="", verbose_name="Identified gaps"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="compliance_level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Compliance level (%)"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("non_compliant", "Non-compliant"),
                    ("partially_compliant", "Partially compliant"),
                    ("compliant", "Compliant"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=25,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="compliance.framework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="guidance",
            field=models.TextField(
                blank=True, default="", verbose_name="Implementation guidance"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="last_assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessed_requirements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last assessor",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="last_assessment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last assessment"
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="linked_assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_requirements",
                to="assets.essentialasset",
                verbose_name="Linked essential assets",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="linked_stakeholder_expectations",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_requirements",
                to="context.stakeholderexpectation",
                verbose_name="Linked stakeholder expectations",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_requirements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="",
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="reference",
            field=models.CharField(max_length=100, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deprecated", "Deprecated"),
                    ("superseded", "Superseded"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="target_date",
            field=models.DateField(blank=True, null=True, verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("recommended", "Recommended"),
                    ("optional", "Optional"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="coverage_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Full"),
                    ("partial", "Partial"),
                    ("minimal", "Minimal"),
                ],
                default="",
                max_length=10,
                verbose_name="Coverage level",
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_mappings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="mapping_type",
            field=models.CharField(
                choices=[
                    ("equivalent", "Equivalent"),
                    ("partial_overlap", "Partial overlap"),
                    ("includes", "Includes"),
                    ("included_by", "Included by"),
                    ("related", "Related"),
                ],
                max_length=20,
                verbose_name="Mapping type",
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="source_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings_as_source",
                to="compliance.requirement",
                verbose_name="Source requirement",
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="target_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings_as_target",
                to="compliance.requirement",
                verbose_name="Target requirement",
            ),
        ),
        migrations.AlterField(
            model_name="requirementmapping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="section",
            name="compliance_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Compliance level (%)",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="section",
            name="framework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="compliance.framework",
                verbose_name="Framework",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="section",
            name="parent_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="compliance.section",
                verbose_name="Parent section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="reference",
            field=models.CharField(max_length=50, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="section",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
