# Generated by Django 5.2.11 on 2026-03-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_alter_assessmentresult_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceactionplan",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="framework",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
