# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0005_alter_complianceactionplan_is_approved_and_more"),
        ("context", "0010_tag_and_tags_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceactionplan",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="framework",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
    ]
