# Generated by Django 5.2.11 on 2026-03-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0006_add_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
    ]
