# Generated by Django 5.2.11 on 2026-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0010_standardise_reference_prefixes"),
        ("context", "0015_scopes_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complianceactionplan",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="complianceassessment",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceactionplan",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceassessment",
            name="scope",
        ),
        migrations.AddField(
            model_name="complianceactionplan",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
    ]
