# Generated by Django 5.2.11 on 2026-03-03 07:56

import re

from django.conf import settings
from django.db import migrations, models


def copy_reference_to_requirement_number(apps, schema_editor):
    """Copy existing requirement.reference values to requirement_number,
    then clear reference so auto-generation can populate it."""
    Requirement = apps.get_model("compliance", "Requirement")
    for req in Requirement.objects.all():
        req.requirement_number = req.reference or ""
        req.reference = ""
        req.save(update_fields=["requirement_number", "reference"])


def generate_auto_references(apps, schema_editor):
    """Generate PREFIX-N references for all compliance models that need them."""
    model_prefixes = [
        ("compliance", "Framework", "FWRK"),
        ("compliance", "Requirement", "REQT"),
        ("compliance", "ComplianceActionPlan", "CAPL"),
    ]
    for app_label, model_name, prefix in model_prefixes:
        Model = apps.get_model(app_label, model_name)
        pattern = re.compile(rf"^{prefix}-\d+$")
        max_num = 0
        for obj in Model.objects.all():
            if obj.reference and pattern.match(obj.reference):
                num = int(obj.reference.split("-")[1])
                if num > max_num:
                    max_num = num
        counter = max_num
        for obj in Model.objects.filter(reference="").order_by("created_at"):
            counter += 1
            obj.reference = f"{prefix}-{counter}"
            obj.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0024_alter_essentialasset_reference_and_more"),
        ("compliance", "0011_scopes_m2m"),
        ("context", "0017_alter_activity_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old constraints
        migrations.RemoveConstraint(
            model_name="requirement",
            name="unique_requirement_reference_per_framework",
        ),
        migrations.RemoveConstraint(
            model_name="section",
            name="unique_section_reference_per_framework",
        ),
        # Step 2: Add requirement_number field
        migrations.AddField(
            model_name="historicalrequirement",
            name="requirement_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Requirement number",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Requirement number",
            ),
        ),
        # Step 3: Alter all fields (requirement.reference WITHOUT unique
        # because data migration below will clear it first)
        migrations.AlterField(
            model_name="requirement",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="complianceactionplan",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalframework",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="reference",
            field=models.CharField(blank=True, max_length=50, verbose_name="Reference"),
        ),
        migrations.AlterField(
            model_name="section",
            name="reference",
            field=models.CharField(blank=True, max_length=50, verbose_name="Reference"),
        ),
        # Step 4: Data migration - copy refs and generate auto-references
        # Must be AFTER schema changes and BEFORE unique constraint (next migration)
        migrations.RunPython(
            copy_reference_to_requirement_number,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            generate_auto_references,
            migrations.RunPython.noop,
        ),
    ]
