# Generated by Django 5.2.12 on 2026-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0014_remove_requirement_order_rename_guidance"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="framework",
            name="logo_16",
            field=models.TextField(blank=True, default="", verbose_name="Logo 16×16"),
        ),
        migrations.AddField(
            model_name="framework",
            name="logo_32",
            field=models.TextField(blank=True, default="", verbose_name="Logo 32×32"),
        ),
        migrations.AddField(
            model_name="framework",
            name="logo_64",
            field=models.TextField(blank=True, default="", verbose_name="Logo 64×64"),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="Logo"),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="logo_16",
            field=models.TextField(blank=True, default="", verbose_name="Logo 16×16"),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="logo_32",
            field=models.TextField(blank=True, default="", verbose_name="Logo 32×32"),
        ),
        migrations.AddField(
            model_name="historicalframework",
            name="logo_64",
            field=models.TextField(blank=True, default="", verbose_name="Logo 64×64"),
        ),
    ]
