# Generated by Django 5.2.12 on 2026-03-08 10:41

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0015_compliancecontrol_controlbody_complianceaudit_and_more"),
        ("context", "0020_indicator_critical_threshold_min_max"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Reference"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval date"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("improvement_opportunity", "Improvement opportunity"),
                            ("observation", "Observation"),
                            ("minor_non_conformity", "Minor non-conformity"),
                            ("major_non_conformity", "Major non-conformity"),
                            ("strength", "Strength"),
                        ],
                        default="observation",
                        max_length=30,
                        verbose_name="Finding type",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, default="", verbose_name="Evidence"),
                ),
                (
                    "action_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="findings",
                        to="compliance.complianceactionplan",
                        verbose_name="Action plans",
                    ),
                ),
                (
                    "activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="findings",
                        to="context.activity",
                        verbose_name="Activities",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_findings",
                        to="compliance.complianceaudit",
                        verbose_name="Audit",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_findings",
                        to="compliance.compliancecontrol",
                        verbose_name="Control",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "related_findings",
                    models.ManyToManyField(
                        blank=True,
                        to="compliance.finding",
                        verbose_name="Related findings",
                    ),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="findings",
                        to="compliance.requirement",
                        verbose_name="Requirements",
                    ),
                ),
                (
                    "scopes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_set",
                        to="context.scope",
                        verbose_name="Scopes",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(app_label)s_%(class)s_set",
                        to="context.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding",
                "verbose_name_plural": "Findings",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalFinding",
            fields=[
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval date"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("improvement_opportunity", "Improvement opportunity"),
                            ("observation", "Observation"),
                            ("minor_non_conformity", "Minor non-conformity"),
                            ("major_non_conformity", "Major non-conformity"),
                            ("strength", "Strength"),
                        ],
                        default="observation",
                        max_length=30,
                        verbose_name="Finding type",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, default="", verbose_name="Evidence"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="compliance.complianceaudit",
                        verbose_name="Audit",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="compliance.compliancecontrol",
                        verbose_name="Control",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Finding",
                "verbose_name_plural": "historical Findings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
