# Generated by Django 5.2.12 on 2026-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0015_framework_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentresult",
            name="gaps",
        ),
        migrations.RemoveField(
            model_name="assessmentresult",
            name="observations",
        ),
        migrations.RemoveField(
            model_name="complianceassessment",
            name="non_compliant_count",
        ),
        migrations.RemoveField(
            model_name="complianceassessment",
            name="partially_compliant_count",
        ),
        migrations.RemoveField(
            model_name="historicalassessmentresult",
            name="gaps",
        ),
        migrations.RemoveField(
            model_name="historicalassessmentresult",
            name="observations",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceassessment",
            name="non_compliant_count",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceassessment",
            name="partially_compliant_count",
        ),
        migrations.RemoveField(
            model_name="historicalrequirement",
            name="compliance_gaps",
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="compliance_gaps",
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="auditor_recommendations",
            field=models.TextField(
                blank=True, default="", verbose_name="Auditor recommendations"
            ),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="finding",
            field=models.TextField(blank=True, default="", verbose_name="Finding"),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="improvement_opportunity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Improvement opportunity"
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="major_non_conformity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Major non-conformity"
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="minor_non_conformity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Minor non-conformity"
            ),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="observation_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Observation"),
        ),
        migrations.AddField(
            model_name="complianceassessment",
            name="strength_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Strength"),
        ),
        migrations.AddField(
            model_name="historicalassessmentresult",
            name="auditor_recommendations",
            field=models.TextField(
                blank=True, default="", verbose_name="Auditor recommendations"
            ),
        ),
        migrations.AddField(
            model_name="historicalassessmentresult",
            name="finding",
            field=models.TextField(blank=True, default="", verbose_name="Finding"),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="improvement_opportunity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Improvement opportunity"
            ),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="major_non_conformity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Major non-conformity"
            ),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="minor_non_conformity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Minor non-conformity"
            ),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="observation_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Observation"),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="strength_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Strength"),
        ),
        migrations.AddField(
            model_name="historicalrequirement",
            name="compliance_finding",
            field=models.TextField(blank=True, default="", verbose_name="Finding"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="compliance_finding",
            field=models.TextField(blank=True, default="", verbose_name="Finding"),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
    ]
