# Generated by Django 5.2.12 on 2026-03-12 12:29

from django.db import migrations


STATUS_MAP = {
    "non_compliant": "major_non_conformity",
    "partially_compliant": "observation",
}


def convert_statuses(apps, schema_editor):
    """Convert old compliance statuses to new ones."""
    AssessmentResult = apps.get_model("compliance", "AssessmentResult")
    Requirement = apps.get_model("compliance", "Requirement")

    for old_status, new_status in STATUS_MAP.items():
        AssessmentResult.objects.filter(compliance_status=old_status).update(
            compliance_status=new_status
        )
        Requirement.objects.filter(compliance_status=old_status).update(
            compliance_status=new_status
        )


def reverse_statuses(apps, schema_editor):
    """Reverse: convert new statuses back to old ones."""
    AssessmentResult = apps.get_model("compliance", "AssessmentResult")
    Requirement = apps.get_model("compliance", "Requirement")

    reverse_map = {v: k for k, v in STATUS_MAP.items()}
    for new_status, old_status in reverse_map.items():
        AssessmentResult.objects.filter(compliance_status=new_status).update(
            compliance_status=old_status
        )
        Requirement.objects.filter(compliance_status=new_status).update(
            compliance_status=old_status
        )


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0016_remove_assessmentresult_gaps_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_statuses, reverse_statuses),
    ]
