# Generated by Django 5.2.12 on 2026-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0019_recreate_finding_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="evaluated_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Evaluated"),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="evaluated_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Evaluated"),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("evaluated", "Evaluated"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessmentresult",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("evaluated", "Evaluated"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("evaluated", "Evaluated"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("not_assessed", "Not assessed"),
                    ("evaluated", "Evaluated"),
                    ("major_non_conformity", "Major non-conformity"),
                    ("minor_non_conformity", "Minor non-conformity"),
                    ("observation", "Observation"),
                    ("improvement_opportunity", "Improvement opportunity"),
                    ("compliant", "Compliant"),
                    ("strength", "Strength"),
                    ("not_applicable", "Not applicable"),
                ],
                default="not_assessed",
                max_length=30,
                verbose_name="Compliance status",
            ),
        ),
    ]
