# Generated by Django 5.2.12 on 2026-03-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0021_rename_evaluated_to_evaluation_planned"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="not_applicable_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Not applicable"),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="not_applicable_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Not applicable"),
        ),
    ]
