# Generated by Django 5.2.12 on 2026-03-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0024_assessment_status_workflow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complianceassessment",
            name="methodology",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceassessment",
            name="methodology",
        ),
    ]
