# Generated by Django 5.2.12 on 2026-03-13 18:53

import compliance.models.assessment
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0025_remove_methodology_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceassessment",
            name="limitations",
            field=models.TextField(blank=True, default="", verbose_name="Limitations"),
        ),
        migrations.AddField(
            model_name="historicalcomplianceassessment",
            name="limitations",
            field=models.TextField(blank=True, default="", verbose_name="Limitations"),
        ),
        migrations.AlterField(
            model_name="complianceassessment",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Context and objectives"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Context and objectives"
            ),
        ),
        migrations.CreateModel(
            name="AssessmentResultAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=compliance.models.assessment._attachment_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "jpeg",
                                    "jpg",
                                    "png",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="File name"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="File size (bytes)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded at"),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="compliance.assessmentresult",
                        verbose_name="Assessment result",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment result attachment",
                "verbose_name_plural": "Assessment result attachments",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
