# Generated by Django 5.2.12 on 2026-03-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0026_add_limitations_and_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Audit draft"),
                    ("planned", "Planned"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Audit draft"),
                    ("planned", "Planned"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
