# Generated by Django 5.2.12 on 2026-03-14 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def convert_old_statuses(apps, schema_editor):
    """Convert old action plan statuses to new kanban statuses."""
    ComplianceActionPlan = apps.get_model("compliance", "ComplianceActionPlan")
    HistoricalComplianceActionPlan = apps.get_model(
        "compliance", "HistoricalComplianceActionPlan"
    )
    STATUS_MAP = {
        "planned": "nouveau",
        "in_progress": "a_implementer",
        "completed": "cloture",
        "cancelled": "annule",
        "overdue": "a_implementer",
    }
    for old_status, new_status in STATUS_MAP.items():
        ComplianceActionPlan.objects.filter(status=old_status).update(status=new_status)
        HistoricalComplianceActionPlan.objects.filter(status=old_status).update(
            status=new_status
        )


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0027_add_cancelled_assessment_status"),
        ("risks", "0014_alter_historicalriskcriteria_risk_matrix_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Widen status field first (to accept new longer values)
        migrations.AlterField(
            model_name="complianceactionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("nouveau", "New"),
                    ("a_definir", "To define"),
                    ("a_valider", "To validate"),
                    ("a_implementer", "To implement"),
                    ("implementation_a_valider", "Implementation to validate"),
                    ("valide", "Validated"),
                    ("cloture", "Closed"),
                    ("annule", "Cancelled"),
                ],
                default="nouveau",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplianceactionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("nouveau", "New"),
                    ("a_definir", "To define"),
                    ("a_valider", "To validate"),
                    ("a_implementer", "To implement"),
                    ("implementation_a_valider", "Implementation to validate"),
                    ("valide", "Validated"),
                    ("cloture", "Closed"),
                    ("annule", "Cancelled"),
                ],
                default="nouveau",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        # 2. Convert old status values to new ones
        migrations.RunPython(convert_old_statuses, migrations.RunPython.noop),
        # 3. Remove old FK fields
        migrations.RemoveField(
            model_name="complianceactionplan",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="complianceactionplan",
            name="requirement",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceactionplan",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="historicalcomplianceactionplan",
            name="requirement",
        ),
        # 4. Add new M2M fields
        migrations.AddField(
            model_name="complianceactionplan",
            name="findings",
            field=models.ManyToManyField(
                blank=True,
                related_name="action_plans",
                to="compliance.finding",
                verbose_name="Linked findings",
            ),
        ),
        migrations.AddField(
            model_name="complianceactionplan",
            name="risks",
            field=models.ManyToManyField(
                blank=True,
                related_name="action_plans",
                to="risks.risk",
                verbose_name="Linked risks",
            ),
        ),
        # 5. Create transition model
        migrations.CreateModel(
            name="ActionPlanTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(max_length=30, verbose_name="From status"),
                ),
                (
                    "to_status",
                    models.CharField(max_length=30, verbose_name="To status"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                (
                    "is_refusal",
                    models.BooleanField(default=False, verbose_name="Is refusal"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "action_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="compliance.complianceactionplan",
                        verbose_name="Action plan",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_plan_transitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action plan transition",
                "verbose_name_plural": "Action plan transitions",
                "ordering": ["-created_at"],
            },
        ),
    ]
