# Generated by Django 5.2.12 on 2026-03-16 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0029_actionplancomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceactionplan",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_action_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assignees",
            ),
        ),
    ]
