# Generated by Django 6.0.2 on 2026-03-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0030_add_assignees_to_action_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceactionplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_action_plans', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='complianceactionplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('to_define', 'To define'), ('to_validate', 'To validate'), ('to_implement', 'To implement'), ('implementation_to_validate', 'Implementation to validate'), ('validated', 'Validated'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceactionplan',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceactionplan',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('to_define', 'To define'), ('to_validate', 'To validate'), ('to_implement', 'To implement'), ('implementation_to_validate', 'Implementation to validate'), ('validated', 'Validated'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
