# Generated by Django 6.0.2 on 2026-03-17 08:56

from django.db import migrations


STATUS_MAPPING = {
    "nouveau": "new",
    "a_definir": "to_define",
    "a_valider": "to_validate",
    "a_implementer": "to_implement",
    "implementation_a_valider": "implementation_to_validate",
    "valide": "validated",
    "cloture": "closed",
    "annule": "cancelled",
}

REVERSE_MAPPING = {v: k for k, v in STATUS_MAPPING.items()}


def migrate_status_forward(apps, schema_editor):
    ActionPlan = apps.get_model("compliance", "ComplianceActionPlan")
    for old, new in STATUS_MAPPING.items():
        ActionPlan.objects.filter(status=old).update(status=new)

    # Also update the transition history table
    Transition = apps.get_model("compliance", "ActionPlanTransition")
    for old, new in STATUS_MAPPING.items():
        Transition.objects.filter(from_status=old).update(from_status=new)
        Transition.objects.filter(to_status=old).update(to_status=new)


def migrate_status_backward(apps, schema_editor):
    ActionPlan = apps.get_model("compliance", "ComplianceActionPlan")
    for new, old in REVERSE_MAPPING.items():
        ActionPlan.objects.filter(status=new).update(status=old)

    Transition = apps.get_model("compliance", "ActionPlanTransition")
    for new, old in REVERSE_MAPPING.items():
        Transition.objects.filter(from_status=new).update(from_status=old)
        Transition.objects.filter(to_status=new).update(to_status=old)


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0031_rename_action_plan_status_to_english'),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
    ]
