# Generated by Django 6.0.2 on 2026-03-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0033_complianceactionplan_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='compliance_status',
            field=models.CharField(choices=[('not_assessed', 'Not assessed'), ('evaluated', 'Evaluation planned'), ('non_compliant', 'Non-compliant'), ('partially_compliant', 'Partially compliant'), ('major_non_conformity', 'Major non-conformity'), ('minor_non_conformity', 'Minor non-conformity'), ('observation', 'Observation'), ('improvement_opportunity', 'Improvement opportunity'), ('compliant', 'Compliant'), ('strength', 'Strength'), ('not_applicable', 'Not applicable')], default='not_assessed', max_length=30, verbose_name='Compliance status'),
        ),
        migrations.AlterField(
            model_name='historicalassessmentresult',
            name='compliance_status',
            field=models.CharField(choices=[('not_assessed', 'Not assessed'), ('evaluated', 'Evaluation planned'), ('non_compliant', 'Non-compliant'), ('partially_compliant', 'Partially compliant'), ('major_non_conformity', 'Major non-conformity'), ('minor_non_conformity', 'Minor non-conformity'), ('observation', 'Observation'), ('improvement_opportunity', 'Improvement opportunity'), ('compliant', 'Compliant'), ('strength', 'Strength'), ('not_applicable', 'Not applicable')], default='not_assessed', max_length=30, verbose_name='Compliance status'),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='compliance_status',
            field=models.CharField(choices=[('not_assessed', 'Not assessed'), ('evaluated', 'Evaluation planned'), ('non_compliant', 'Non-compliant'), ('partially_compliant', 'Partially compliant'), ('major_non_conformity', 'Major non-conformity'), ('minor_non_conformity', 'Minor non-conformity'), ('observation', 'Observation'), ('improvement_opportunity', 'Improvement opportunity'), ('compliant', 'Compliant'), ('strength', 'Strength'), ('not_applicable', 'Not applicable')], default='not_assessed', max_length=30, verbose_name='Compliance status'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='compliance_status',
            field=models.CharField(choices=[('not_assessed', 'Not assessed'), ('evaluated', 'Evaluation planned'), ('non_compliant', 'Non-compliant'), ('partially_compliant', 'Partially compliant'), ('major_non_conformity', 'Major non-conformity'), ('minor_non_conformity', 'Minor non-conformity'), ('observation', 'Observation'), ('improvement_opportunity', 'Improvement opportunity'), ('compliant', 'Compliant'), ('strength', 'Strength'), ('not_applicable', 'Not applicable')], default='not_assessed', max_length=30, verbose_name='Compliance status'),
        ),
    ]
