# Generated by Django 6.0.2 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0035_complianceactionplan_originating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceactionplan',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='finding',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='framework',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalcomplianceactionplan',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalcomplianceassessment',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalfinding',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalframework',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalrequirement',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
