# Generated by Django 5.2.12 on 2026-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VersioningConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Django model label, e.g. 'context.scope'",
                        max_length=100,
                        unique=True,
                        verbose_name="Model identifier",
                    ),
                ),
                (
                    "model_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Display name"
                    ),
                ),
                (
                    "approval_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When disabled, approval workflow is hidden for this item type.",
                        verbose_name="Approval enabled",
                    ),
                ),
                (
                    "major_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field names whose modification triggers a version increment and approval reset. If empty, all field changes are considered major.",
                        verbose_name="Major change fields",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versioning configuration",
                "verbose_name_plural": "Versioning configurations",
                "ordering": ["model_name"],
            },
        ),
    ]
