# Generated by Django 6.0.2 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_versioning_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioningconfig',
            name='workflow_name',
            field=models.CharField(blank=True, help_text='Name of the lifecycle workflow for this item type. Leave blank to use the default workflow.', max_length=100, verbose_name='Workflow'),
        ),
    ]
