# Generated by Django 5.2.11 on 2026-02-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_scope_add_parent_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['name'], 'verbose_name': 'Périmètre', 'verbose_name_plural': 'Périmètres'},
        ),
    ]
