# Generated by Django 5.2.11 on 2026-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='excluded_sites',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_scopes', to='context.site', verbose_name='Sites exclus'),
        ),
        migrations.AddField(
            model_name='scope',
            name='included_sites',
            field=models.ManyToManyField(blank=True, related_name='included_in_scopes', to='context.site', verbose_name='Sites inclus'),
        ),
    ]
