# Generated by Django 5.2.11 on 2026-02-28 15:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0007_scope_add_sites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "Activity", "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="historicalactivity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Activity",
                "verbose_name_plural": "historical Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalissue",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Issue",
                "verbose_name_plural": "historical Issues",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalobjective",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Objective",
                "verbose_name_plural": "historical Objectives",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresponsibility",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Responsibility",
                "verbose_name_plural": "historical Responsibilities",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrole",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Role",
                "verbose_name_plural": "historical Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalscope",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Scope",
                "verbose_name_plural": "historical Scopes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstakeholder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Stakeholder",
                "verbose_name_plural": "historical Stakeholders",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstakeholderexpectation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Expectation",
                "verbose_name_plural": "historical Expectations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalswotanalysis",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical SWOT analysis",
                "verbose_name_plural": "historical SWOT analyses",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalswotitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical SWOT item",
                "verbose_name_plural": "historical SWOT items",
            },
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"verbose_name": "Issue", "verbose_name_plural": "Issues"},
        ),
        migrations.AlterModelOptions(
            name="objective",
            options={"verbose_name": "Objective", "verbose_name_plural": "Objectives"},
        ),
        migrations.AlterModelOptions(
            name="responsibility",
            options={
                "ordering": ["role", "raci_type"],
                "verbose_name": "Responsibility",
                "verbose_name_plural": "Responsibilities",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="scope",
            options={
                "ordering": ["name"],
                "verbose_name": "Scope",
                "verbose_name_plural": "Scopes",
            },
        ),
        migrations.AlterModelOptions(
            name="stakeholder",
            options={
                "verbose_name": "Stakeholder",
                "verbose_name_plural": "Stakeholders",
            },
        ),
        migrations.AlterModelOptions(
            name="stakeholderexpectation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Expectation",
                "verbose_name_plural": "Expectations",
            },
        ),
        migrations.AlterModelOptions(
            name="swotanalysis",
            options={
                "verbose_name": "SWOT analysis",
                "verbose_name_plural": "SWOT analyses",
            },
        ),
        migrations.AlterModelOptions(
            name="swotitem",
            options={
                "ordering": ["quadrant", "order"],
                "verbose_name": "SWOT item",
                "verbose_name_plural": "SWOT items",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Criticality",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="parent_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="context.activity",
                verbose_name="Parent activity",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="reference",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="related_objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_activities",
                to="context.objective",
                verbose_name="Contributing objectives",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="related_stakeholders",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_activities",
                to="context.stakeholder",
                verbose_name="Stakeholders",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("planned", "Planned"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("core_business", "Core business"),
                    ("support", "Support"),
                    ("management", "Management"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Criticality",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="parent_activity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.activity",
                verbose_name="Parent activity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("planned", "Planned"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="type",
            field=models.CharField(
                choices=[
                    ("core_business", "Core business"),
                    ("support", "Support"),
                    ("management", "Management"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="category",
            field=models.CharField(
                choices=[
                    ("strategic", "Strategic"),
                    ("organizational", "Organizational"),
                    ("human_resources", "Human resources"),
                    ("technical", "Technical"),
                    ("financial", "Financial"),
                    ("cultural", "Cultural"),
                    ("political", "Political"),
                    ("economic", "Economic"),
                    ("social", "Social"),
                    ("technological", "Technological"),
                    ("legal", "Legal"),
                    ("environmental", "Environmental"),
                    ("competitive", "Competitive"),
                    ("regulatory", "Regulatory"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="impact_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Impact level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("active", "Active"),
                    ("monitored", "Monitored"),
                    ("closed", "Closed"),
                ],
                default="identified",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="trend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("improving", "Improving"),
                    ("stable", "Stable"),
                    ("degrading", "Degrading"),
                ],
                default="",
                max_length=20,
                verbose_name="Trend",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="type",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="category",
            field=models.CharField(
                choices=[
                    ("confidentiality", "Confidentiality"),
                    ("integrity", "Integrity"),
                    ("availability", "Availability"),
                    ("compliance", "Compliance"),
                    ("operational", "Operational"),
                    ("strategic", "Strategic"),
                ],
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="current_value",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Current value"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="measurement_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi_annual", "Semi-annual"),
                    ("annual", "Annual"),
                ],
                default="",
                max_length=20,
                verbose_name="Measurement frequency",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="measurement_method",
            field=models.TextField(
                blank=True, default="", verbose_name="Measurement method"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="parent_objective",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.objective",
                verbose_name="Parent objective",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="progress_percentage",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progress (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("achieved", "Achieved"),
                    ("not_achieved", "Not achieved"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="target_date",
            field=models.DateField(blank=True, null=True, verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="target_value",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Target value"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="type",
            field=models.CharField(
                choices=[
                    ("security", "Security"),
                    ("compliance", "Compliance"),
                    ("business", "Business"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="unit",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Unit of measure"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponsibility",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponsibility",
            name="raci_type",
            field=models.CharField(
                choices=[
                    ("responsible", "Responsible (R)"),
                    ("accountable", "Accountable (A)"),
                    ("consulted", "Consulted (C)"),
                    ("informed", "Informed (I)"),
                ],
                max_length=20,
                verbose_name="RACI type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponsibility",
            name="related_activity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.activity",
                verbose_name="Related activity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponsibility",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.role",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresponsibility",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="is_mandatory",
            field=models.BooleanField(default=False, verbose_name="Mandatory role"),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="source_standard",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Source standard"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="type",
            field=models.CharField(
                choices=[
                    ("governance", "Governance"),
                    ("operational", "Operational"),
                    ("support", "Support"),
                    ("control", "Control"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="boundaries",
            field=models.TextField(
                blank=True, default="", verbose_name="Boundaries and exclusions"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="effective_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Effective date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="geographic_scope",
            field=models.TextField(
                blank=True, default="", verbose_name="Geographic scope"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="justification_exclusions",
            field=models.TextField(
                blank=True, default="", verbose_name="Justification for exclusions"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="organizational_scope",
            field=models.TextField(
                blank=True, default="", verbose_name="Organizational scope"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="parent_scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Parent scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="technical_scope",
            field=models.TextField(
                blank=True, default="", verbose_name="Technical scope"
            ),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="parent_site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.site",
                verbose_name="Parent site",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="type",
            field=models.CharField(
                choices=[
                    ("siege", "Headquarters"),
                    ("bureau", "Office"),
                    ("usine", "Factory"),
                    ("entrepot", "Warehouse"),
                    ("datacenter", "Datacenter"),
                    ("site_distant", "Remote site"),
                    ("autre", "Other"),
                ],
                default="autre",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="category",
            field=models.CharField(
                choices=[
                    ("executive_management", "Executive management"),
                    ("employees", "Employees"),
                    ("customers", "Customers"),
                    ("suppliers", "Suppliers"),
                    ("partners", "Partners"),
                    ("regulators", "Regulators"),
                    ("shareholders", "Shareholders"),
                    ("insurers", "Insurers"),
                    ("public", "General public"),
                    ("competitors", "Competitors"),
                    ("unions", "Unions"),
                    ("auditors", "Auditors"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Contact email"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="contact_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Contact name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Contact phone"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="influence_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
                verbose_name="Influence level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="interest_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
                verbose_name="Interest level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="type",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholderexpectation",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholderexpectation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholderexpectation",
            name="stakeholder",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.stakeholder",
                verbose_name="Stakeholder",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholderexpectation",
            name="type",
            field=models.CharField(
                choices=[
                    ("requirement", "Requirement"),
                    ("expectation", "Expectation"),
                    ("need", "Need"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstakeholderexpectation",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="analysis_date",
            field=models.DateField(verbose_name="Analysis date"),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("validated", "Validated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Validation date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotitem",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotitem",
            name="impact_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
                verbose_name="Impact level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotitem",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="historicalswotitem",
            name="quadrant",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("weakness", "Weakness"),
                    ("opportunity", "Opportunity"),
                    ("threat", "Threat"),
                ],
                max_length=20,
                verbose_name="Quadrant",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotitem",
            name="swot_analysis",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.swotanalysis",
                verbose_name="SWOT analysis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalswotitem",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.CharField(
                choices=[
                    ("strategic", "Strategic"),
                    ("organizational", "Organizational"),
                    ("human_resources", "Human resources"),
                    ("technical", "Technical"),
                    ("financial", "Financial"),
                    ("cultural", "Cultural"),
                    ("political", "Political"),
                    ("economic", "Economic"),
                    ("social", "Social"),
                    ("technological", "Technological"),
                    ("legal", "Legal"),
                    ("environmental", "Environmental"),
                    ("competitive", "Competitive"),
                    ("regulatory", "Regulatory"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="impact_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Impact level",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="related_stakeholders",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_issues",
                to="context.stakeholder",
                verbose_name="Related stakeholders",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("active", "Active"),
                    ("monitored", "Monitored"),
                    ("closed", "Closed"),
                ],
                default="identified",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="trend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("improving", "Improving"),
                    ("stable", "Stable"),
                    ("degrading", "Degrading"),
                ],
                default="",
                max_length=20,
                verbose_name="Trend",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="type",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="category",
            field=models.CharField(
                choices=[
                    ("confidentiality", "Confidentiality"),
                    ("integrity", "Integrity"),
                    ("availability", "Availability"),
                    ("compliance", "Compliance"),
                    ("operational", "Operational"),
                    ("strategic", "Strategic"),
                ],
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="current_value",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Current value"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="measurement_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi_annual", "Semi-annual"),
                    ("annual", "Annual"),
                ],
                default="",
                max_length=20,
                verbose_name="Measurement frequency",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="measurement_method",
            field=models.TextField(
                blank=True, default="", verbose_name="Measurement method"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_objectives",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="parent_objective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="context.objective",
                verbose_name="Parent objective",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="progress_percentage",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Progress (%)",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="reference",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="related_issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_objectives",
                to="context.issue",
                verbose_name="Addressed issues",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="related_stakeholders",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_objectives",
                to="context.stakeholder",
                verbose_name="Stakeholders",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("achieved", "Achieved"),
                    ("not_achieved", "Not achieved"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="target_date",
            field=models.DateField(blank=True, null=True, verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="target_value",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Target value"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="type",
            field=models.CharField(
                choices=[
                    ("security", "Security"),
                    ("compliance", "Compliance"),
                    ("business", "Business"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="unit",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Unit of measure"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="raci_type",
            field=models.CharField(
                choices=[
                    ("responsible", "Responsible (R)"),
                    ("accountable", "Accountable (A)"),
                    ("consulted", "Consulted (C)"),
                    ("informed", "Informed (I)"),
                ],
                max_length=20,
                verbose_name="RACI type",
            ),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="related_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsibilities",
                to="context.activity",
                verbose_name="Related activity",
            ),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibilities",
                to="context.role",
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="role",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="context_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned users",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_mandatory",
            field=models.BooleanField(default=False, verbose_name="Mandatory role"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="role",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="source_standard",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Source standard"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="type",
            field=models.CharField(
                choices=[
                    ("governance", "Governance"),
                    ("operational", "Operational"),
                    ("support", "Support"),
                    ("control", "Control"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="boundaries",
            field=models.TextField(
                blank=True, default="", verbose_name="Boundaries and exclusions"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="effective_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Effective date"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="excluded_sites",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_from_scopes",
                to="context.site",
                verbose_name="Excluded sites",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="geographic_scope",
            field=models.TextField(
                blank=True, default="", verbose_name="Geographic scope"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="included_sites",
            field=models.ManyToManyField(
                blank=True,
                related_name="included_in_scopes",
                to="context.site",
                verbose_name="Included sites",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="justification_exclusions",
            field=models.TextField(
                blank=True, default="", verbose_name="Justification for exclusions"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="organizational_scope",
            field=models.TextField(
                blank=True, default="", verbose_name="Organizational scope"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="parent_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="context.scope",
                verbose_name="Parent scope",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="technical_scope",
            field=models.TextField(
                blank=True, default="", verbose_name="Technical scope"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="site",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="site",
            name="parent_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="context.site",
                verbose_name="Parent site",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="type",
            field=models.CharField(
                choices=[
                    ("siege", "Headquarters"),
                    ("bureau", "Office"),
                    ("usine", "Factory"),
                    ("entrepot", "Warehouse"),
                    ("datacenter", "Datacenter"),
                    ("site_distant", "Remote site"),
                    ("autre", "Other"),
                ],
                default="autre",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="category",
            field=models.CharField(
                choices=[
                    ("executive_management", "Executive management"),
                    ("employees", "Employees"),
                    ("customers", "Customers"),
                    ("suppliers", "Suppliers"),
                    ("partners", "Partners"),
                    ("regulators", "Regulators"),
                    ("shareholders", "Shareholders"),
                    ("insurers", "Insurers"),
                    ("public", "General public"),
                    ("competitors", "Competitors"),
                    ("unions", "Unions"),
                    ("auditors", "Auditors"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Contact email"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="contact_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Contact name"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Contact phone"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="influence_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
                verbose_name="Influence level",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="interest_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
                verbose_name="Interest level",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="type",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="stakeholderexpectation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="stakeholderexpectation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholderexpectation",
            name="stakeholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expectations",
                to="context.stakeholder",
                verbose_name="Stakeholder",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholderexpectation",
            name="type",
            field=models.CharField(
                choices=[
                    ("requirement", "Requirement"),
                    ("expectation", "Expectation"),
                    ("need", "Need"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholderexpectation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="analysis_date",
            field=models.DateField(verbose_name="Analysis date"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("validated", "Validated"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Validation date"
            ),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_swot_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validated by",
            ),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="impact_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
                verbose_name="Impact level",
            ),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="quadrant",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("weakness", "Weakness"),
                    ("opportunity", "Opportunity"),
                    ("threat", "Threat"),
                ],
                max_length=20,
                verbose_name="Quadrant",
            ),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="related_issues",
            field=models.ManyToManyField(
                blank=True,
                related_name="swot_items",
                to="context.issue",
                verbose_name="Related issues",
            ),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="related_objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="swot_items",
                to="context.objective",
                verbose_name="Related objectives",
            ),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="swot_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="context.swotanalysis",
                verbose_name="SWOT analysis",
            ),
        ),
        migrations.AlterField(
            model_name="swotitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
