# Generated by Django 5.2.11 on 2026-03-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0008_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalrole",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalscope",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalsite",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalswotanalysis",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="site",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="swotanalysis",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
