# Generated by Django 5.2.11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0009_alter_activity_is_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                ("color", models.CharField(default="#6c757d", help_text="Hex color code, e.g. #ff5733", max_length=7, verbose_name="Color")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="objective",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="role",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="scope",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="site",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="swotanalysis",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
    ]
