# Generated by Django 5.2.11 on 2026-03-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0010_tag_and_tags_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalissue",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalrole",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalscope",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalsite",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalstakeholder",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalswotanalysis",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="scope",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="swotanalysis",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
    ]
