# Generated by Django 5.2.11 on 2026-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0015_scopes_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalscope",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bootstrap Icons class name (e.g. bi-building, bi-globe, bi-shield-lock).",
                max_length=50,
                verbose_name="Icon",
            ),
        ),
        migrations.AddField(
            model_name="scope",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bootstrap Icons class name (e.g. bi-building, bi-globe, bi-shield-lock).",
                max_length=50,
                verbose_name="Icon",
            ),
        ),
    ]
