# Generated by Django 5.2.11 on 2026-03-03 07:56

import re

from django.db import migrations, models


def regenerate_manual_references(apps, schema_editor):
    """Regenerate references that were manually entered (not matching PREFIX-N pattern)."""
    model_prefixes = [
        ("context", "Activity", "ACTV"),
        ("context", "Objective", "OBJT"),
    ]
    for app_label, model_name, prefix in model_prefixes:
        Model = apps.get_model(app_label, model_name)
        pattern = re.compile(rf"^{prefix}-\d+$")
        max_num = 0
        for obj in Model.objects.all():
            if obj.reference and pattern.match(obj.reference):
                num = int(obj.reference.split("-")[1])
                if num > max_num:
                    max_num = num
        counter = max_num
        for obj in Model.objects.order_by("created_at"):
            if not obj.reference or not pattern.match(obj.reference):
                counter += 1
                obj.reference = f"{prefix}-{counter}"
                obj.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0016_scope_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalactivity",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.RunPython(
            regenerate_manual_references,
            migrations.RunPython.noop,
        ),
    ]
