# Generated by Django 5.2.11 on 2026-03-03 09:59

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0017_alter_activity_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalIndicator",
            fields=[
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval date"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("organizational", "Organizational"),
                            ("technical", "Technical"),
                        ],
                        max_length=20,
                        verbose_name="Indicator type",
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "API"),
                            ("internal", "Internal Open GRC"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Collection method",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("number", "Number"), ("boolean", "Boolean")],
                        default="number",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Applicable only for number format.",
                        max_length=50,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "current_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Current value",
                    ),
                ),
                (
                    "expected_level",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Expected level",
                    ),
                ),
                (
                    "critical_threshold_operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("below", "Falls below"),
                            ("above", "Exceeds"),
                            ("is_false", "Is false"),
                            ("is_true", "Is true"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Critical threshold",
                    ),
                ),
                (
                    "critical_threshold_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For numbers only. For booleans, the operator defines the threshold.",
                        max_length=255,
                        verbose_name="Critical threshold value",
                    ),
                ),
                (
                    "review_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-annual"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                        verbose_name="Review frequency",
                    ),
                ),
                (
                    "first_review_date",
                    models.DateField(verbose_name="First review date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="Internal Open GRC indicator"
                    ),
                ),
                (
                    "internal_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("global_compliance_rate", "Global compliance rate"),
                            (
                                "framework_compliance_rate",
                                "Compliance rate by framework",
                            ),
                            ("objective_progress", "Objective progress rate"),
                            ("risk_treatment_rate", "Risk treatment rate"),
                            ("approved_scopes_rate", "Approved scopes rate"),
                            (
                                "mandatory_roles_coverage",
                                "Mandatory roles coverage rate",
                            ),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Internal data source",
                    ),
                ),
                (
                    "internal_source_parameter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional parameter, e.g. framework ID for compliance rate by framework.",
                        max_length=255,
                        verbose_name="Source parameter",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Indicator",
                "verbose_name_plural": "historical Indicators",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Reference"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval date"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("organizational", "Organizational"),
                            ("technical", "Technical"),
                        ],
                        max_length=20,
                        verbose_name="Indicator type",
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "API"),
                            ("internal", "Internal Open GRC"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Collection method",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("number", "Number"), ("boolean", "Boolean")],
                        default="number",
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Applicable only for number format.",
                        max_length=50,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "current_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Current value",
                    ),
                ),
                (
                    "expected_level",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Expected level",
                    ),
                ),
                (
                    "critical_threshold_operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("below", "Falls below"),
                            ("above", "Exceeds"),
                            ("is_false", "Is false"),
                            ("is_true", "Is true"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Critical threshold",
                    ),
                ),
                (
                    "critical_threshold_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For numbers only. For booleans, the operator defines the threshold.",
                        max_length=255,
                        verbose_name="Critical threshold value",
                    ),
                ),
                (
                    "review_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-annual"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                        verbose_name="Review frequency",
                    ),
                ),
                (
                    "first_review_date",
                    models.DateField(verbose_name="First review date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="Internal Open GRC indicator"
                    ),
                ),
                (
                    "internal_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("global_compliance_rate", "Global compliance rate"),
                            (
                                "framework_compliance_rate",
                                "Compliance rate by framework",
                            ),
                            ("objective_progress", "Objective progress rate"),
                            ("risk_treatment_rate", "Risk treatment rate"),
                            ("approved_scopes_rate", "Approved scopes rate"),
                            (
                                "mandatory_roles_coverage",
                                "Mandatory roles coverage rate",
                            ),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Internal data source",
                    ),
                ),
                (
                    "internal_source_parameter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional parameter, e.g. framework ID for compliance rate by framework.",
                        max_length=255,
                        verbose_name="Source parameter",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "scopes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_set",
                        to="context.scope",
                        verbose_name="Scopes",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(app_label)s_%(class)s_set",
                        to="context.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator",
                "verbose_name_plural": "Indicators",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndicatorMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recorded at"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="context.indicator",
                        verbose_name="Indicator",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicator_measurements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator measurement",
                "verbose_name_plural": "Indicator measurements",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
