# Generated by Django 5.2.11 on 2026-03-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0018_add_indicator_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalindicator",
            name="collection_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("api", "API"),
                    ("internal", "Predefined Open GRC"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Collection method",
            ),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="internal_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("global_compliance_rate", "Global compliance rate"),
                    ("framework_compliance_rate", "Compliance rate by framework"),
                    ("objective_progress", "Objective progress rate"),
                    ("risk_treatment_rate", "Risk treatment rate"),
                    ("approved_scopes_rate", "Approved scopes rate"),
                    ("mandatory_roles_coverage", "Mandatory roles coverage rate"),
                ],
                default="",
                max_length=50,
                verbose_name="Predefined data source",
            ),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="is_internal",
            field=models.BooleanField(
                default=False, verbose_name="Predefined Open GRC indicator"
            ),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="review_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi_annual", "Semi-annual"),
                    ("annual", "Annual"),
                ],
                max_length=20,
                verbose_name="Review frequency",
            ),
        ),
        migrations.AlterField(
            model_name="historicalobjective",
            name="measurement_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi_annual", "Semi-annual"),
                    ("annual", "Annual"),
                ],
                default="",
                max_length=20,
                verbose_name="Measurement frequency",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="collection_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("api", "API"),
                    ("internal", "Predefined Open GRC"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Collection method",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="internal_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("global_compliance_rate", "Global compliance rate"),
                    ("framework_compliance_rate", "Compliance rate by framework"),
                    ("objective_progress", "Objective progress rate"),
                    ("risk_treatment_rate", "Risk treatment rate"),
                    ("approved_scopes_rate", "Approved scopes rate"),
                    ("mandatory_roles_coverage", "Mandatory roles coverage rate"),
                ],
                default="",
                max_length=50,
                verbose_name="Predefined data source",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="is_internal",
            field=models.BooleanField(
                default=False, verbose_name="Predefined Open GRC indicator"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="review_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi_annual", "Semi-annual"),
                    ("annual", "Annual"),
                ],
                max_length=20,
                verbose_name="Review frequency",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="measurement_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi_annual", "Semi-annual"),
                    ("annual", "Annual"),
                ],
                default="",
                max_length=20,
                verbose_name="Measurement frequency",
            ),
        ),
    ]
