# Generated by Django 5.2.11 on 2026-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0019_alter_historicalindicator_collection_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="critical_threshold_min",
            field=models.FloatField(
                blank=True,
                help_text="Critical if the value falls below this minimum (numbers only).",
                null=True,
                verbose_name="Minimum threshold",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="critical_threshold_max",
            field=models.FloatField(
                blank=True,
                help_text="Critical if the value exceeds this maximum (numbers only).",
                null=True,
                verbose_name="Maximum threshold",
            ),
        ),
        migrations.AddField(
            model_name="historicalindicator",
            name="critical_threshold_min",
            field=models.FloatField(
                blank=True,
                help_text="Critical if the value falls below this minimum (numbers only).",
                null=True,
                verbose_name="Minimum threshold",
            ),
        ),
        migrations.AddField(
            model_name="historicalindicator",
            name="critical_threshold_max",
            field=models.FloatField(
                blank=True,
                help_text="Critical if the value exceeds this maximum (numbers only).",
                null=True,
                verbose_name="Maximum threshold",
            ),
        ),
    ]
