# Generated by Django 5.2.12 on 2026-03-10 19:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0020_indicator_critical_threshold_min_max"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSwotStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "quadrant",
                    models.CharField(
                        choices=[
                            ("so", "SO — Leverage"),
                            ("st", "ST — Confront"),
                            ("wo", "WO — Improve"),
                            ("wt", "WT — Avoid"),
                        ],
                        max_length=2,
                        verbose_name="Strategy quadrant",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "swot_analysis",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="context.swotanalysis",
                        verbose_name="SWOT analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical SWOT strategy",
                "verbose_name_plural": "historical SWOT strategies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SwotStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quadrant",
                    models.CharField(
                        choices=[
                            ("so", "SO — Leverage"),
                            ("st", "ST — Confront"),
                            ("wo", "WO — Improve"),
                            ("wt", "WT — Avoid"),
                        ],
                        max_length=2,
                        verbose_name="Strategy quadrant",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "swot_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="context.swotanalysis",
                        verbose_name="SWOT analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT strategy",
                "verbose_name_plural": "SWOT strategies",
                "ordering": ["quadrant", "order"],
            },
        ),
    ]
