# Generated by Django 6.0.2 on 2026-06-01

"""Make IndicatorMeasurement.recorded_at user-writable (QA report CAIRN-IND-03).

The field was previously auto_now_add=True, which let Django set it on insert
but rejected any explicit value. Switching to default=timezone.now keeps the
current-time default behaviour while letting API / MCP callers backdate
historical measurement series. db_index is added because the field is the
canonical sort key for the measurements queryset.

The verbose_name AlterField operations that makemigrations also produced for
collection_method / is_internal stem from the post-rebrand string changes
("Predefined Open GRC" -> "Predefined Cairn"). They are unrelated to this
ticket and are intentionally excluded so the migration stays focused.
"""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0024_historicalobjective_originating_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatormeasurement",
            name="recorded_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Recorded at",
            ),
        ),
    ]
