# Generated by Django 6.0.2 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0029_cairn_rebrand_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalobjective',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalscope',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalstakeholder',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalstakeholderfeedback',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalswotanalysis',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='issue',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='objective',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='role',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='scope',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='site',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='stakeholderfeedback',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
