# Generated by Django 6.0.2 on 2026-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identifiant unique de la page ou fonctionnalité (ex: context.scope_list).', max_length=100, verbose_name='Clé')),
                ('language', models.CharField(default='fr', help_text='Code langue ISO 639-1 (ex: fr, en).', max_length=10, verbose_name='Langue')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Contenu d'aide",
                'verbose_name_plural': "Contenus d'aide",
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
