# Generated by Django 5.2.11 on 2026-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpers", "0003_complete_help_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="helpcontent",
            options={
                "ordering": ["key", "language"],
                "verbose_name": "Help content",
                "verbose_name_plural": "Help contents",
            },
        ),
        migrations.AlterField(
            model_name="helpcontent",
            name="body",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="helpcontent",
            name="key",
            field=models.CharField(
                help_text="Unique identifier of the page or feature (e.g. context.scope_list).",
                max_length=100,
                verbose_name="Key",
            ),
        ),
        migrations.AlterField(
            model_name="helpcontent",
            name="language",
            field=models.CharField(
                default="fr",
                help_text="ISO 639-1 language code (e.g. fr, en).",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="helpcontent",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="helpcontent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last modified"),
        ),
    ]
