# Generated by Django 5.2.11 on 2026-02-28 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_rename_version_add_version"),
        ("context", "0008_alter_activity_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetdependency",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Dependency relationship",
                "verbose_name_plural": "Dependency relationships",
            },
        ),
        migrations.AlterModelOptions(
            name="assetgroup",
            options={
                "verbose_name": "Asset group",
                "verbose_name_plural": "Asset groups",
            },
        ),
        migrations.AlterModelOptions(
            name="assetvaluation",
            options={
                "ordering": ["-evaluation_date", "-created_at"],
                "verbose_name": "DIC valuation",
                "verbose_name_plural": "DIC valuations",
            },
        ),
        migrations.AlterModelOptions(
            name="essentialasset",
            options={
                "verbose_name": "Essential asset",
                "verbose_name_plural": "Essential assets",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassetdependency",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Dependency relationship",
                "verbose_name_plural": "historical Dependency relationships",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassetgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Asset group",
                "verbose_name_plural": "historical Asset groups",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassetvaluation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical DIC valuation",
                "verbose_name_plural": "historical DIC valuations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalessentialasset",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Essential asset",
                "verbose_name_plural": "historical Essential assets",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsupportasset",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Support asset",
                "verbose_name_plural": "historical Support assets",
            },
        ),
        migrations.AlterModelOptions(
            name="supportasset",
            options={
                "verbose_name": "Support asset",
                "verbose_name_plural": "Support assets",
            },
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_dependencies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dependencies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Criticality",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="dependency_type",
            field=models.CharField(
                choices=[
                    ("runs_on", "Runs on"),
                    ("stored_in", "Stored in"),
                    ("transmitted_by", "Transmitted by"),
                    ("managed_by", "Managed by"),
                    ("hosted_at", "Hosted at"),
                    ("protected_by", "Protected by"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Dependency type",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="essential_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies_as_essential",
                to="assets.essentialasset",
                verbose_name="Essential asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="is_single_point_of_failure",
            field=models.BooleanField(
                default=False, verbose_name="Single point of failure (SPOF)"
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="redundancy_level",
            field=models.CharField(
                blank=True,
                choices=[("none", "None"), ("partial", "Partial"), ("full", "Full")],
                default="",
                max_length=20,
                verbose_name="Redundancy level",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="support_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies_as_support",
                to="assets.supportasset",
                verbose_name="Support asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetdependency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                to="assets.supportasset",
                verbose_name="Members",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_asset_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("network", "Network"),
                    ("person", "Person"),
                    ("site", "Site"),
                    ("service", "Service"),
                    ("paper", "Paper"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="availability_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="confidentiality_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                verbose_name="Confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="context",
            field=models.TextField(blank=True, default="", verbose_name="Context"),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="essential_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valuations",
                to="assets.essentialasset",
                verbose_name="Essential asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="evaluated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asset_valuations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Evaluator",
            ),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="evaluation_date",
            field=models.DateField(verbose_name="Evaluation date"),
        ),
        migrations.AlterField(
            model_name="assetvaluation",
            name="integrity_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                verbose_name="Integrity",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="availability_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Availability justification"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="availability_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=2,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("core_process", "Core business process"),
                    ("support_process", "Support process"),
                    ("management_process", "Management process"),
                    ("strategic_data", "Strategic data"),
                    ("operational_data", "Operational data"),
                    ("personal_data", "Personal data"),
                    ("financial_data", "Financial data"),
                    ("technical_data", "Technical data"),
                    ("legal_data", "Legal data"),
                    ("research_data", "Research data"),
                    ("commercial_data", "Commercial data"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="confidentiality_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Confidentiality justification"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="confidentiality_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=2,
                verbose_name="Confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custodian_essential_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Custodian",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="data_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Public"),
                    ("internal", "Internal"),
                    ("confidential", "Confidential"),
                    ("restricted", "Restricted"),
                    ("secret", "Secret"),
                ],
                default="",
                max_length=20,
                verbose_name="Classification",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="integrity_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Integrity justification"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="integrity_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=2,
                verbose_name="Integrity",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="max_tolerable_downtime",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="MTD / Max tolerable downtime",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_essential_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="personal_data",
            field=models.BooleanField(default=False, verbose_name="Personal data"),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="personal_data_categories",
            field=models.JSONField(
                blank=True, null=True, verbose_name="GDPR categories"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="reference",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="regulatory_constraints",
            field=models.TextField(
                blank=True, default="", verbose_name="Regulatory constraints"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="related_activities",
            field=models.ManyToManyField(
                blank=True,
                related_name="essential_assets",
                to="context.activity",
                verbose_name="Business activities",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("active", "Active"),
                    ("under_review", "Under review"),
                    ("decommissioned", "Decommissioned"),
                ],
                default="identified",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("business_process", "Business process"),
                    ("information", "Information"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="essentialasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="Criticality",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="dependency_type",
            field=models.CharField(
                choices=[
                    ("runs_on", "Runs on"),
                    ("stored_in", "Stored in"),
                    ("transmitted_by", "Transmitted by"),
                    ("managed_by", "Managed by"),
                    ("hosted_at", "Hosted at"),
                    ("protected_by", "Protected by"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Dependency type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="essential_asset",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="assets.essentialasset",
                verbose_name="Essential asset",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="is_single_point_of_failure",
            field=models.BooleanField(
                default=False, verbose_name="Single point of failure (SPOF)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="redundancy_level",
            field=models.CharField(
                blank=True,
                choices=[("none", "None"), ("partial", "Partial"), ("full", "Full")],
                default="",
                max_length=20,
                verbose_name="Redundancy level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="support_asset",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="assets.supportasset",
                verbose_name="Support asset",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetdependency",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("network", "Network"),
                    ("person", "Person"),
                    ("site", "Site"),
                    ("service", "Service"),
                    ("paper", "Paper"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetgroup",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="availability_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="confidentiality_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                verbose_name="Confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="context",
            field=models.TextField(blank=True, default="", verbose_name="Context"),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="essential_asset",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="assets.essentialasset",
                verbose_name="Essential asset",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="evaluated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Evaluator",
            ),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="evaluation_date",
            field=models.DateField(verbose_name="Evaluation date"),
        ),
        migrations.AlterField(
            model_name="historicalassetvaluation",
            name="integrity_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                verbose_name="Integrity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="availability_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Availability justification"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="availability_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=2,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("core_process", "Core business process"),
                    ("support_process", "Support process"),
                    ("management_process", "Management process"),
                    ("strategic_data", "Strategic data"),
                    ("operational_data", "Operational data"),
                    ("personal_data", "Personal data"),
                    ("financial_data", "Financial data"),
                    ("technical_data", "Technical data"),
                    ("legal_data", "Legal data"),
                    ("research_data", "Research data"),
                    ("commercial_data", "Commercial data"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="confidentiality_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Confidentiality justification"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="confidentiality_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=2,
                verbose_name="Confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Custodian",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="data_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Public"),
                    ("internal", "Internal"),
                    ("confidential", "Confidential"),
                    ("restricted", "Restricted"),
                    ("secret", "Secret"),
                ],
                default="",
                max_length=20,
                verbose_name="Classification",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="integrity_justification",
            field=models.TextField(
                blank=True, default="", verbose_name="Integrity justification"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="integrity_level",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=2,
                verbose_name="Integrity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="max_tolerable_downtime",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="MTD / Max tolerable downtime",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="personal_data",
            field=models.BooleanField(default=False, verbose_name="Personal data"),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="personal_data_categories",
            field=models.JSONField(
                blank=True, null=True, verbose_name="GDPR categories"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="regulatory_constraints",
            field=models.TextField(
                blank=True, default="", verbose_name="Regulatory constraints"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("active", "Active"),
                    ("under_review", "Under review"),
                    ("decommissioned", "Decommissioned"),
                ],
                default="identified",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("business_process", "Business process"),
                    ("information", "Information"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalessentialasset",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="acquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Acquisition date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("server", "Server"),
                    ("workstation", "Workstation"),
                    ("laptop", "Laptop"),
                    ("mobile_device", "Mobile device"),
                    ("network_equipment", "Network equipment"),
                    ("storage", "Storage"),
                    ("peripheral", "Peripheral"),
                    ("iot_device", "IoT device"),
                    ("removable_media", "Removable media"),
                    ("other_hardware", "Other hardware"),
                    ("operating_system", "Operating system"),
                    ("database", "Database"),
                    ("application", "Application"),
                    ("middleware", "Middleware"),
                    ("security_tool", "Security tool"),
                    ("development_tool", "Development tool"),
                    ("saas_application", "SaaS application"),
                    ("other_software", "Other software"),
                    ("lan", "Local area network (LAN)"),
                    ("wan", "Wide area network (WAN)"),
                    ("wifi", "Wi-Fi"),
                    ("vpn", "VPN"),
                    ("internet_link", "Internet link"),
                    ("firewall_zone", "Firewall zone"),
                    ("dmz", "DMZ"),
                    ("other_network", "Other network"),
                    ("internal_staff", "Internal staff"),
                    ("contractor", "Contractor"),
                    ("external_provider", "External provider"),
                    ("administrator", "Administrator"),
                    ("developer", "Developer"),
                    ("other_person", "Other person"),
                    ("datacenter", "Datacenter"),
                    ("office", "Office"),
                    ("remote_site", "Remote site"),
                    ("cloud_region", "Cloud region"),
                    ("other_site", "Other site"),
                    ("cloud_service", "Cloud service"),
                    ("hosting_service", "Hosting service"),
                    ("managed_service", "Managed service"),
                    ("telecom_service", "Telecom service"),
                    ("outsourced_service", "Outsourced service"),
                    ("other_service", "Other service"),
                    ("archive", "Archive"),
                    ("printed_document", "Printed document"),
                    ("form", "Form"),
                    ("other_paper", "Other paper"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="contract_reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Contract reference",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Custodian",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="end_of_life_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="End of life date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", "Production"),
                    ("staging", "Staging"),
                    ("development", "Development"),
                    ("test", "Test"),
                    ("disaster_recovery", "Disaster recovery"),
                ],
                default="",
                max_length=20,
                verbose_name="Environment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="exposure_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internal", "Internal"),
                    ("exposed", "Exposed"),
                    ("internet_facing", "Internet-facing"),
                    ("dmz", "DMZ"),
                ],
                default="",
                max_length=20,
                verbose_name="Exposure level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="hostname",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Hostname"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="inherited_availability",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                verbose_name="Inherited availability",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="inherited_confidentiality",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                verbose_name="Inherited confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="inherited_integrity",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                verbose_name="Inherited integrity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="ip_address",
            field=models.CharField(
                blank=True, default="", max_length=45, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Manufacturer / vendor",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="model_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Model / version"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="operating_system",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Operating system"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="parent_asset",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="assets.supportasset",
                verbose_name="Parent support asset",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="serial_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Serial number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="software_version",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Software version"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("deployed", "Deployed"),
                    ("active", "Active"),
                    ("under_maintenance", "Under maintenance"),
                    ("decommissioned", "Decommissioned"),
                    ("disposed", "Disposed"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("network", "Network"),
                    ("person", "Person"),
                    ("site", "Site"),
                    ("service", "Service"),
                    ("paper", "Paper"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportasset",
            name="warranty_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Warranty expiry"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="acquisition_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Acquisition date"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approval date"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("server", "Server"),
                    ("workstation", "Workstation"),
                    ("laptop", "Laptop"),
                    ("mobile_device", "Mobile device"),
                    ("network_equipment", "Network equipment"),
                    ("storage", "Storage"),
                    ("peripheral", "Peripheral"),
                    ("iot_device", "IoT device"),
                    ("removable_media", "Removable media"),
                    ("other_hardware", "Other hardware"),
                    ("operating_system", "Operating system"),
                    ("database", "Database"),
                    ("application", "Application"),
                    ("middleware", "Middleware"),
                    ("security_tool", "Security tool"),
                    ("development_tool", "Development tool"),
                    ("saas_application", "SaaS application"),
                    ("other_software", "Other software"),
                    ("lan", "Local area network (LAN)"),
                    ("wan", "Wide area network (WAN)"),
                    ("wifi", "Wi-Fi"),
                    ("vpn", "VPN"),
                    ("internet_link", "Internet link"),
                    ("firewall_zone", "Firewall zone"),
                    ("dmz", "DMZ"),
                    ("other_network", "Other network"),
                    ("internal_staff", "Internal staff"),
                    ("contractor", "Contractor"),
                    ("external_provider", "External provider"),
                    ("administrator", "Administrator"),
                    ("developer", "Developer"),
                    ("other_person", "Other person"),
                    ("datacenter", "Datacenter"),
                    ("office", "Office"),
                    ("remote_site", "Remote site"),
                    ("cloud_region", "Cloud region"),
                    ("other_site", "Other site"),
                    ("cloud_service", "Cloud service"),
                    ("hosting_service", "Hosting service"),
                    ("managed_service", "Managed service"),
                    ("telecom_service", "Telecom service"),
                    ("outsourced_service", "Outsourced service"),
                    ("other_service", "Other service"),
                    ("archive", "Archive"),
                    ("printed_document", "Printed document"),
                    ("form", "Form"),
                    ("other_paper", "Other paper"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="contract_reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Contract reference",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="custodian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custodian_support_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Custodian",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="end_of_life_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="End of life date"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", "Production"),
                    ("staging", "Staging"),
                    ("development", "Development"),
                    ("test", "Test"),
                    ("disaster_recovery", "Disaster recovery"),
                ],
                default="",
                max_length=20,
                verbose_name="Environment",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="exposure_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internal", "Internal"),
                    ("exposed", "Exposed"),
                    ("internet_facing", "Internet-facing"),
                    ("dmz", "DMZ"),
                ],
                default="",
                max_length=20,
                verbose_name="Exposure level",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="hostname",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Hostname"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="inherited_availability",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                verbose_name="Inherited availability",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="inherited_confidentiality",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                verbose_name="Inherited confidentiality",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="inherited_integrity",
            field=models.IntegerField(
                choices=[
                    (0, "Negligible"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                verbose_name="Inherited integrity",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="ip_address",
            field=models.CharField(
                blank=True, default="", max_length=45, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Manufacturer / vendor",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="model_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Model / version"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="operating_system",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Operating system"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_support_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="parent_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="assets.supportasset",
                verbose_name="Parent support asset",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="reference",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next review date"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scope",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="serial_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Serial number"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="software_version",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Software version"
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("deployed", "Deployed"),
                    ("active", "Active"),
                    ("under_maintenance", "Under maintenance"),
                    ("decommissioned", "Decommissioned"),
                    ("disposed", "Disposed"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="type",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("network", "Network"),
                    ("person", "Person"),
                    ("site", "Site"),
                    ("service", "Service"),
                    ("paper", "Paper"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="supportasset",
            name="warranty_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Warranty expiry"
            ),
        ),
    ]
