# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_alter_assetdependency_is_approved_and_more"),
        ("context", "0010_tag_and_tags_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgroup",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="essentialasset",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="supportasset",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
    ]
