# Generated by Django 5.2.11 on 2026-03-01 09:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_standardise_reference_prefixes"),
        ("compliance", "0010_standardise_reference_prefixes"),
        ("context", "0014_shorten_reference_prefixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Updated at"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval date"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Reference"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cloud_provider", "Cloud provider"),
                            ("software_vendor", "Software vendor"),
                            ("hardware_vendor", "Hardware vendor"),
                            ("consulting", "Consulting"),
                            ("managed_services", "Managed services"),
                            ("telecommunications", "Telecommunications"),
                            ("outsourcing", "Outsourcing"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Criticality",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contact name",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Contact email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Contact phone",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="Website"),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Address"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contract reference",
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract start date"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract end date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("under_evaluation", "Under evaluation"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="context.scope",
                        verbose_name="Scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Supplier",
                "verbose_name_plural": "historical Suppliers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval date"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Reference"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cloud_provider", "Cloud provider"),
                            ("software_vendor", "Software vendor"),
                            ("hardware_vendor", "Hardware vendor"),
                            ("consulting", "Consulting"),
                            ("managed_services", "Managed services"),
                            ("telecommunications", "Telecommunications"),
                            ("outsourcing", "Outsourcing"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Criticality",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contact name",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Contact email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Contact phone",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="Website"),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Address"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contract reference",
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract start date"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contract end date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("under_evaluation", "Under evaluation"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_suppliers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="context.scope",
                        verbose_name="Scope",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(app_label)s_%(class)s_set",
                        to="context.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Custom title when not linked to a compliance requirement.",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("not_assessed", "Not assessed"),
                            ("compliant", "Compliant"),
                            ("partially_compliant", "Partially compliant"),
                            ("non_compliant", "Non-compliant"),
                        ],
                        default="not_assessed",
                        max_length=25,
                        verbose_name="Compliance status",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, default="", verbose_name="Evidence"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_requirements",
                        to="compliance.requirement",
                        verbose_name="Linked requirement",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="assets.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_supplier_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier requirement",
                "verbose_name_plural": "Supplier requirements",
                "ordering": ["-created_at"],
            },
        ),
    ]
