# Generated by Django 5.2.11 on 2026-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_add_supplier_dependency"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupplier",
            name="logo",
            field=models.TextField(
                blank=True, default="", max_length=100, verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="suppliers/logos/",
                verbose_name="Logo",
            ),
        ),
    ]
