# Generated by Django 5.2.11 on 2026-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0014_supplier_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupplierdependency",
            name="is_single_point_of_failure",
            field=models.BooleanField(
                default=False, verbose_name="Single point of failure (SPOF)"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierdependency",
            name="redundancy_level",
            field=models.CharField(
                blank=True,
                choices=[("none", "None"), ("partial", "Partial"), ("full", "Full")],
                default="",
                max_length=20,
                verbose_name="Redundancy level",
            ),
        ),
        migrations.AddField(
            model_name="supplierdependency",
            name="is_single_point_of_failure",
            field=models.BooleanField(
                default=False, verbose_name="Single point of failure (SPOF)"
            ),
        ),
        migrations.AddField(
            model_name="supplierdependency",
            name="redundancy_level",
            field=models.CharField(
                blank=True,
                choices=[("none", "None"), ("partial", "Partial"), ("full", "Full")],
                default="",
                max_length=20,
                verbose_name="Redundancy level",
            ),
        ),
    ]
