# Generated by Django 5.2.11 on 2026-03-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0015_supplier_dependency_spof"),
        ("compliance", "0010_standardise_reference_prefixes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supplier_types",
                        to="compliance.requirement",
                        verbose_name="Default requirements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier type",
                "verbose_name_plural": "Supplier types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="historicalsupplier",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="assets.suppliertype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="assets.suppliertype",
                verbose_name="Type",
            ),
        ),
    ]
