# Generated by Django 5.2.11 on 2026-03-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0016_supplier_type_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierTypeRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "supplier_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="assets.suppliertype",
                        verbose_name="Supplier type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier type requirement",
                "verbose_name_plural": "Supplier type requirements",
                "ordering": ["title"],
            },
        ),
    ]
