# Generated by Django 5.2.11 on 2026-03-01 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0017_supplier_type_requirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierRequirementReview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("review_date", models.DateField(verbose_name="Review date")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("not_assessed", "Not assessed"),
                            ("compliant", "Compliant"),
                            ("partially_compliant", "Partially compliant"),
                            ("non_compliant", "Non-compliant"),
                        ],
                        default="not_assessed",
                        max_length=25,
                        verbose_name="Result",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Written justification for the compliance assessment.",
                        verbose_name="Justification",
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="Upload a supporting document (certificate, report, etc.).",
                        upload_to="supplier_requirements/evidence/",
                        verbose_name="Supporting evidence",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_requirement_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "supplier_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="assets.supplierrequirement",
                        verbose_name="Supplier requirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement review",
                "verbose_name_plural": "Requirement reviews",
                "ordering": ["-review_date", "-created_at"],
            },
        ),
    ]
