# Generated by Django 5.2.11 on 2026-03-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0018_supplier_requirement_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierrequirement",
            name="source_type_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instantiated_requirements",
                to="assets.suppliertyperequirement",
                verbose_name="Source type requirement",
            ),
        ),
    ]
