# Generated by Django 5.2.11 on 2026-03-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0020_add_site_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierrequirementreview",
            name="evidence_filename",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Evidence filename"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupplier",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="supplierrequirementreview",
            name="evidence_file",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Upload a supporting document (certificate, report, etc.).",
                verbose_name="Supporting evidence",
            ),
        ),
    ]
