# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0021_supplierrequirementreview_evidence_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="logo_16",
            field=models.TextField(
                blank=True, default="", verbose_name="Logo 16\u00d716"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="logo_32",
            field=models.TextField(
                blank=True, default="", verbose_name="Logo 32\u00d732"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="logo_64",
            field=models.TextField(
                blank=True, default="", verbose_name="Logo 64\u00d764"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplier",
            name="logo_16",
            field=models.TextField(
                blank=True, default="", verbose_name="Logo 16\u00d716"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplier",
            name="logo_32",
            field=models.TextField(
                blank=True, default="", verbose_name="Logo 32\u00d732"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplier",
            name="logo_64",
            field=models.TextField(
                blank=True, default="", verbose_name="Logo 64\u00d764"
            ),
        ),
    ]
