# Generated by Django 5.2.11 on 2026-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0022_add_logo_variants"),
        ("context", "0015_scopes_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetgroup",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="essentialasset",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalassetgroup",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalessentialasset",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalsupplier",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalsupportasset",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="supportasset",
            name="scope",
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="essentialasset",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="supportasset",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
    ]
