# Generated by Django 5.2.11 on 2026-03-03 08:48

import re

from django.db import migrations, models


def generate_auto_references(apps, schema_editor):
    """Generate PREFIX-N references for all new models that need them."""
    model_prefixes = [
        ("assets", "SupplierType", "SPTY"),
        ("assets", "AssetDependency", "ADEP"),
        ("assets", "SupplierDependency", "SDEP"),
        ("assets", "SiteAssetDependency", "SADP"),
        ("assets", "SiteSupplierDependency", "SSDP"),
    ]
    for app_label, model_name, prefix in model_prefixes:
        Model = apps.get_model(app_label, model_name)
        pattern = re.compile(rf"^{prefix}-\d+$")
        max_num = 0
        for obj in Model.objects.all():
            if obj.reference and pattern.match(obj.reference):
                num = int(obj.reference.split("-")[1])
                if num > max_num:
                    max_num = num
        counter = max_num
        for obj in Model.objects.filter(reference="").order_by("pk"):
            counter += 1
            obj.reference = f"{prefix}-{counter}"
            obj.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0024_alter_essentialasset_reference_and_more"),
    ]

    operations = [
        # Step 1: Add reference fields WITHOUT unique constraint
        migrations.AddField(
            model_name="assetdependency",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalassetdependency",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalsiteassetdependency",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalsitesupplierdependency",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierdependency",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="siteassetdependency",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="sitesupplierdependency",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="supplierdependency",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="suppliertype",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Reference"
            ),
        ),
        # Step 2: Populate references for existing rows
        migrations.RunPython(
            generate_auto_references,
            migrations.RunPython.noop,
        ),
    ]
