# Generated by Django 6.0.2 on 2026-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_add_reference_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitesupplierdependency',
            name='dependency_type',
            field=models.CharField(choices=[('provides', 'Provides'), ('hosts', 'Hosts'), ('manages', 'Manages'), ('develops', 'Develops'), ('supports', 'Supports'), ('licenses', 'Licenses'), ('maintains', 'Maintains'), ('other', 'Other')], max_length=20, verbose_name='Dependency type'),
        ),
        migrations.AlterField(
            model_name='historicalsupplierdependency',
            name='dependency_type',
            field=models.CharField(choices=[('provides', 'Provides'), ('hosts', 'Hosts'), ('manages', 'Manages'), ('develops', 'Develops'), ('supports', 'Supports'), ('licenses', 'Licenses'), ('maintains', 'Maintains'), ('other', 'Other')], max_length=20, verbose_name='Dependency type'),
        ),
        migrations.AlterField(
            model_name='sitesupplierdependency',
            name='dependency_type',
            field=models.CharField(choices=[('provides', 'Provides'), ('hosts', 'Hosts'), ('manages', 'Manages'), ('develops', 'Develops'), ('supports', 'Supports'), ('licenses', 'Licenses'), ('maintains', 'Maintains'), ('other', 'Other')], max_length=20, verbose_name='Dependency type'),
        ),
        migrations.AlterField(
            model_name='supplierdependency',
            name='dependency_type',
            field=models.CharField(choices=[('provides', 'Provides'), ('hosts', 'Hosts'), ('manages', 'Manages'), ('develops', 'Develops'), ('supports', 'Supports'), ('licenses', 'Licenses'), ('maintains', 'Maintains'), ('other', 'Other')], max_length=20, verbose_name='Dependency type'),
        ),
    ]
