# Generated by Django 6.0.2 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_drop_supportasset_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroup',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='essentialasset',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalassetgroup',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalessentialasset',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalsupportasset',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='supportasset',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
