# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0005_alter_historicaliso27005risk_is_approved_and_more"),
        ("context", "0010_tag_and_tags_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="iso27005risk",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="risk",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="riskacceptance",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="riskcriteria",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="risktreatmentplan",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="threat",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="%(app_label)s_%(class)s_set", to="context.tag", verbose_name="Tags"),
        ),
    ]
