# Generated by Django 5.2.11 on 2026-03-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0006_add_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaliso27005risk",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalriskacceptance",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="historicalriskcriteria",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="iso27005risk",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="riskacceptance",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="riskcriteria",
            name="reference",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reference"
            ),
        ),
    ]
