# Generated by Django 5.2.11 on 2026-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0015_scopes_m2m"),
        ("risks", "0010_standardise_reference_prefixes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalriskassessment",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalriskcriteria",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalthreat",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="historicalvulnerability",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="riskassessment",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="riskcriteria",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="threat",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="vulnerability",
            name="scope",
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="riskcriteria",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="threat",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_set",
                to="context.scope",
                verbose_name="Scopes",
            ),
        ),
    ]
