# Generated by Django 5.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0013_requirement_reference_unique_and_constraints"),
        ("risks", "0012_alter_historicalrisk_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="linked_requirements",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_risks",
                to="compliance.requirement",
                verbose_name="Linked requirements",
            ),
        ),
    ]
