# Generated by Django 5.2.12 on 2026-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0013_risk_linked_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalriskcriteria",
            name="risk_matrix",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Risk matrix"
            ),
        ),
        migrations.AlterField(
            model_name="riskcriteria",
            name="risk_matrix",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Risk matrix"
            ),
        ),
    ]
