# Generated by Django 6.0.2 on 2026-06-02

"""Add `other` to Threat.category choices (closes the THR-01 schema half).

When the QA report flagged that `ThreatCategory` was missing an
`OTHER` value (CAIRN-THR-01 / issue #52), the constant was added
in commit 4c001b3 but no migration captured the choices refresh
on the threat / historicalthreat fields. Tests didn't catch it
because settings_test builds the schema from the live model rather
than replaying migrations; production caught it as a permanent
"unapplied changes" warning at container boot. Pure choices-metadata
update, no DB schema change.
"""

from django.db import migrations, models


THREAT_CATEGORY_CHOICES = [
    ('malware', 'Malware'),
    ('social_engineering', 'Social engineering'),
    ('unauthorized_access', 'Unauthorized access'),
    ('denial_of_service', 'Denial of service'),
    ('data_breach', 'Data breach'),
    ('physical_attack', 'Physical attack'),
    ('espionage', 'Espionage'),
    ('fraud', 'Fraud'),
    ('sabotage', 'Sabotage'),
    ('human_error', 'Human error'),
    ('system_failure', 'System failure'),
    ('network_failure', 'Network failure'),
    ('power_failure', 'Power failure'),
    ('natural_disaster', 'Natural disaster'),
    ('fire', 'Fire'),
    ('water_damage', 'Water damage'),
    ('theft', 'Theft'),
    ('vandalism', 'Vandalism'),
    ('supply_chain', 'Supply chain'),
    ('insider_threat', 'Insider threat'),
    ('ransomware', 'Ransomware'),
    ('apt', 'Advanced persistent threat (APT)'),
    ('other', 'Other'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0024_backfill_ebios_summary_for_existing_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalthreat',
            name='category',
            field=models.CharField(blank=True, choices=THREAT_CATEGORY_CHOICES, max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='category',
            field=models.CharField(blank=True, choices=THREAT_CATEGORY_CHOICES, max_length=30, verbose_name='Category'),
        ),
    ]
