# Generated by Django 6.0.2 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0025_threat_category_add_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackpathstep',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='attacktechnique',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='baselinegap',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='ebiossummary',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='ebiosworkshopprogress',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='ecosystemstakeholder',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='fearedevent',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalattackpathstep',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalattacktechnique',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalbaselinegap',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalebiossummary',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalebiosworkshopprogress',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalecosystemstakeholder',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalfearedevent',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicaliso27005risk',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicaloperationalscenario',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalpacsmeasure',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalrisk',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalriskacceptance',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalriskassessment',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalriskcriteria',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalrisksource',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalrisksourceobjectivepair',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalrisktreatmentplan',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalsecuritybaseline',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalstrategicscenario',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalstudyframework',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicaltargetedobjective',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalthreat',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='historicalvulnerability',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='iso27005risk',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='operationalscenario',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='pacsmeasure',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='risk',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='riskacceptance',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='riskcriteria',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='risksource',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='risksourceobjectivepair',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='risktreatmentplan',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='securitybaseline',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='strategicscenario',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='studyframework',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='targetedobjective',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='threat',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='workflow_state',
            field=models.CharField(db_index=True, default='draft', help_text='Current state of the element in its lifecycle workflow.', max_length=32, verbose_name='Lifecycle state'),
        ),
    ]
