# Generated by Django 6.0.2 on 2026-02-27 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text='Format : module.feature.action', max_length=255, unique=True, verbose_name='Code technique')),
                ('name', models.CharField(max_length=255, verbose_name='Libellé')),
                ('module', models.CharField(db_index=True, max_length=100, verbose_name='Module')),
                ('feature', models.CharField(db_index=True, max_length=100, verbose_name='Feature')),
                ('action', models.CharField(choices=[('create', 'Créer'), ('read', 'Lire'), ('update', 'Modifier'), ('delete', 'Supprimer'), ('access', 'Accéder')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_system', models.BooleanField(default=True, verbose_name='Permission système')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'feature', 'action'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('job_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Fonction')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='Service')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives échouées')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Verrouillé jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('email_attempted', models.CharField(db_index=True, max_length=255, verbose_name='Email utilisé')),
                ('event_type', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Connexion échouée'), ('logout', 'Déconnexion'), ('token_refresh', 'Rafraîchissement de token'), ('password_change', 'Changement de mot de passe'), ('account_locked', 'Compte verrouillé'), ('account_unlocked', 'Compte déverrouillé')], db_index=True, max_length=30, verbose_name="Type d'événement")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_password', 'Mot de passe invalide'), ('account_locked', 'Compte verrouillé'), ('account_inactive', 'Compte inactif'), ('user_not_found', 'Utilisateur introuvable')], default='', max_length=30, verbose_name="Raison de l'échec")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal des accès',
                'verbose_name_plural': 'Journal des accès',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, verbose_name='Groupe système')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('users', models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
                ('permissions', models.ManyToManyField(blank=True, related_name='groups', to='accounts.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
    ]
