# Generated by Django 5.2.11 on 2026-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_compliance_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('create', 'Créer'), ('read', 'Lire'), ('update', 'Modifier'), ('delete', 'Supprimer'), ('access', 'Accéder'), ('approve', 'Approuver')], max_length=20, verbose_name='Action'),
        ),
    ]
