# Generated by Django 5.2.11 on 2026-02-28 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_risks_permissions"),
        ("context", "0008_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesslog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Access log",
                "verbose_name_plural": "Access logs",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["name"],
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="email_attempted",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Email used"
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Successful login"),
                    ("login_failed", "Failed login"),
                    ("logout", "Logout"),
                    ("token_refresh", "Token refresh"),
                    ("password_change", "Password change"),
                    ("account_locked", "Account locked"),
                    ("account_unlocked", "Account unlocked"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Event type",
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invalid_password", "Invalid password"),
                    ("account_locked", "Account locked"),
                    ("account_inactive", "Inactive account"),
                    ("user_not_found", "User not found"),
                ],
                default="",
                max_length=30,
                verbose_name="Failure reason",
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="allowed_scopes",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_groups",
                to="context.scope",
                verbose_name="Allowed scopes",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="System group"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("read", "Read"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("access", "Access"),
                    ("approve", "Approve"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="codename",
            field=models.CharField(
                help_text="Format: module.feature.action",
                max_length=255,
                unique=True,
                verbose_name="Codename",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="is_system",
            field=models.BooleanField(default=True, verbose_name="System permission"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Department"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Failed attempts"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="Django admin access"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Job title"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("", "Auto (browser)"), ("fr", "Français"), ("en", "English")],
                default="",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Locked until"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last password change"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="Europe/Paris", max_length=50, verbose_name="Timezone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
