# Generated by Django 5.2.11 on 2026-03-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_accesslog_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="avatars/",
                verbose_name="Profile photo",
            ),
        ),
    ]
