# Generated by Django 5.2.11 on 2026-03-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(
                blank=True, default="", verbose_name="Profile photo"
            ),
        ),
    ]
