# Generated by Django 5.2.11 on 2026-03-02 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Successful login"),
                    ("login_failed", "Failed login"),
                    ("logout", "Logout"),
                    ("token_refresh", "Token refresh"),
                    ("password_change", "Password change"),
                    ("account_locked", "Account locked"),
                    ("account_unlocked", "Account unlocked"),
                    ("passkey_login_success", "Passkey login"),
                    ("passkey_login_failed", "Passkey login failed"),
                    ("passkey_registered", "Passkey registered"),
                    ("passkey_deleted", "Passkey deleted"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Event type",
            ),
        ),
        migrations.CreateModel(
            name="Passkey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "credential_id",
                    models.BinaryField(unique=True, verbose_name="Credential ID"),
                ),
                ("public_key", models.BinaryField(verbose_name="Public key")),
                (
                    "sign_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sign count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last used at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey",
                "verbose_name_plural": "Passkeys",
                "ordering": ["-created_at"],
            },
        ),
    ]
