# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_16",
            field=models.TextField(
                blank=True, default="", verbose_name="Avatar 16\u00d716"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_32",
            field=models.TextField(
                blank=True, default="", verbose_name="Avatar 32\u00d732"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_64",
            field=models.TextField(
                blank=True, default="", verbose_name="Avatar 64\u00d764"
            ),
        ),
    ]
