# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_avatar_variants"),
        ("accounts", "0012_alter_accesslog_event_type_passkey"),
    ]

    operations = []
