# Generated by Django 5.2.12 on 2026-03-13 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_dashboard_indicators"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Company name",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Address"),
                ),
                ("logo", models.TextField(blank=True, default="", verbose_name="Logo")),
                (
                    "logo_32",
                    models.TextField(blank=True, default="", verbose_name="Logo 32×32"),
                ),
                (
                    "logo_64",
                    models.TextField(blank=True, default="", verbose_name="Logo 64×64"),
                ),
                (
                    "logo_128",
                    models.TextField(
                        blank=True, default="", verbose_name="Logo 128×128"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Company settings",
                "verbose_name_plural": "Company settings",
            },
        ),
    ]
