# Generated by Django 6.0.2 on 2026-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_action_plan_workflow_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='Calendar subscription token'),
        ),
    ]
