# Generated by Django 6.0.2 on 2026-03-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_calendar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Calendar token created at'),
        ),
    ]
