# Generated by Django 6.0.2 on 2026-03-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_add_calendar_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token_last_used_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Calendar token last used at'),
        ),
    ]
