# Generated by Django 6.0.2 on 2026-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_calendar_token_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_token_last_user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Calendar token last user agent'),
        ),
    ]
