# Generated by Django 6.0.2 on 2026-03-17 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_calendar_token_last_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calendar_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calendar_token_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calendar_token_last_used_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calendar_token_last_user_agent',
        ),
        migrations.CreateModel(
            name='CalendarToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last used at')),
                ('last_user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='Last user agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Calendar token',
                'verbose_name_plural': 'Calendar tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
