# Generated by Django 6.0.2 on 2026-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_add_assets_config_create_delete_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_version',
            field=models.CharField(blank=True, default='', help_text='App version last acknowledged by the user in the changelog popup.', max_length=20, verbose_name='Last seen version'),
        ),
    ]
