# Generated by Django 6.0.2 on 2026-06-11 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_add_theme_preference'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Also receive in-app notifications by email.', verbose_name='Email notifications'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('lifecycle_submitted', 'Element pending validation')], db_index=True, max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('target_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Target URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx')],
            },
        ),
    ]
