# Generated by Django 5.2.11 on 2026-03-02 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthapplication",
            name="redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON-encoded list of allowed redirect URIs for public clients.",
                verbose_name="Redirect URIs (JSON)",
            ),
        ),
        migrations.AddField(
            model_name="oauthapplication",
            name="token_endpoint_auth_method",
            field=models.CharField(
                default="client_secret_post",
                max_length=20,
                verbose_name="Token endpoint auth method",
            ),
        ),
        migrations.AlterField(
            model_name="oauthapplication",
            name="client_secret_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Client secret (hashed)",
            ),
        ),
        migrations.CreateModel(
            name="OAuthAuthorizationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Code (hashed)",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="Client ID"),
                ),
                (
                    "redirect_uri",
                    models.URLField(max_length=2048, verbose_name="Redirect URI"),
                ),
                (
                    "code_challenge",
                    models.CharField(
                        max_length=128, verbose_name="PKCE code challenge"
                    ),
                ),
                (
                    "code_challenge_method",
                    models.CharField(
                        default="S256",
                        max_length=10,
                        verbose_name="PKCE code challenge method",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="Scope"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_authorization_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth authorization code",
                "verbose_name_plural": "OAuth authorization codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
