# Generated by Django 5.2.12 on 2026-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0002_oauthapplication_redirect_uris_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthauthorizationcode",
            name="redirect_uri",
            field=models.CharField(max_length=2048, verbose_name="Redirect URI"),
        ),
    ]
