# Generated by Django 5.2.12 on 2026-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="file_content",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="File content"
            ),
        ),
        migrations.AddField(
            model_name="historicalreport",
            name="file_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="File name"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="file_content",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="File content"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="file_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="File name"
            ),
        ),
    ]
