# Generated by Django 5.2.12 on 2026-03-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0025_remove_methodology_field"),
        ("reports", "0002_historicalreport_file_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreport",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compliance.complianceassessment",
                verbose_name="Assessment",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="compliance.complianceassessment",
                verbose_name="Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("soa", "Statement of Applicability"),
                    ("audit_report", "Audit report"),
                ],
                max_length=30,
                verbose_name="Report type",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("soa", "Statement of Applicability"),
                    ("audit_report", "Audit report"),
                ],
                max_length=30,
                verbose_name="Report type",
            ),
        ),
    ]
