# Generated by Django 6.0.6 on 2026-06-13 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=40, verbose_name='Content type')),
                ('object_id', models.UUIDField(verbose_name='Object id')),
                ('text', models.TextField(verbose_name='Embedded text')),
                ('content_hash', models.CharField(max_length=64, verbose_name='Content hash')),
                ('embedding', models.JSONField(default=list, verbose_name='Embedding')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Embedding model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Semantic index entry',
                'verbose_name_plural': 'Semantic index entries',
                'indexes': [models.Index(fields=['content_type'], name='assistant_s_content_289a97_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_semantic_object')],
            },
        ),
    ]
